ir_types = [
    "interest rate contract",
    "interest rate forward contract",
    "interest rate collar contract",
    "interest rate swap contract",
    "zero coupon swap contract",
    "single currency basis swap contract",
    "interest rate future contract",
    "pay-fixed, receive-floating interest rate swap contract",
    "pay-floating, receive-fixed interest rate swap contract",
    "interest rate hedge contract",
    "interest rate hedge agreement",
    "forward starting interest rate swap contract",
    "treasury rate lock agreement",
    "interest rate swap agreement",
]

ir_entry_templates = [
    "In {month} {year}, {swap_type} were entered into and designated as hedges of the notes with a notional amount of {currency_code}{notional} {money_unit}, effectively converting portions of fixed-rate debt to floating rates",
    "During {month} {year}, {company} executed {swap_type} with an aggregate notional value of {currency_code}{notional} {money_unit} to modify the interest rate characteristics of outstanding senior notes",
    "{company} entered into {swap_type} in {month} {year} with a total notional amount of {currency_code}{notional} {money_unit}, designated as fair value hedges of fixed-rate obligations",
    "In {month} {year}, {swap_type} totaling {currency_code}{notional} {money_unit} notional were designated as hedging instruments against changes in the fair value of fixed-rate debt",
    "{company} executed {swap_type} in {month} {year} with notional amounts aggregating {currency_code}{notional} {money_unit} to hedge interest rate exposure on a portion of its debt portfolio",
    "in the {quarter} quarter of {year}, {company} entered into {swap_type} with a notional value of {currency_code}{notional} {money_unit} to convert fixed-rate senior notes to variable rates",
    "During {month} {year}, {swap_type} were executed with a total notional amount of {currency_code}{notional} {money_unit} to manage interest rate risk on long-term debt",
    "In {month} {year}, {company} designated {swap_type} with a notional amount of {currency_code}{notional} {money_unit} as fair value hedges for its outstanding bonds",
    "{company} initiated {swap_type} in {month} {year} with a notional value of {currency_code}{notional} {money_unit} to adjust the interest rate profile of its debt",
    "in the {quarter} quarter of {year}, {swap_type} totaling {currency_code}{notional} {money_unit} were entered to hedge changes in the fair value of fixed-rate liabilities",
    "During {month} {year}, {company} executed {swap_type} with a notional amount of {currency_code}{notional} {money_unit} to manage exposure to interest rate fluctuations",
    "In {month} {year}, {swap_type} with an aggregate notional value of {currency_code}{notional} {money_unit} were designated to hedge fixed-rate debt obligations",
    "{company} entered into {swap_type} in the {quarter} quarter of {year} with a notional amount of {currency_code}{notional} {money_unit} to modify the interest rate structure of its senior notes",
    "In {month} {year}, {swap_type} were implemented with a total notional value of {currency_code}{notional} {money_unit} to hedge the fair value of outstanding debt",
    "During {year}, {company} executed {swap_type} with a notional amount of {currency_code}{notional} {money_unit} to convert portions of its fixed-rate debt to floating rates",
    "In {month} {year}, {swap_type} with a notional value of {currency_code}{notional} {money_unit} were designated as fair value hedges against changes in debt valuation",
    "{company} entered into {swap_type} during the {quarter} quarter of {year} with a notional amount of {currency_code}{notional} {money_unit} to manage interest rate exposure on bonds",
    "In {month} {year}, {swap_type} totaling {currency_code}{notional} {money_unit} were executed to adjust the interest rate characteristics of long-term liabilities",
    "during the {quarter} quarter of {year}, {company} designated {swap_type} with a notional value of {currency_code}{notional} {money_unit} as hedges of fixed-rate note obligations",
    "In {month} {year}, {swap_type} were entered with a total notional amount of {currency_code}{notional} {money_unit} to mitigate interest rate risk on debt issuances",
]

ir_past_event_templates = [
    "During {month} {year}, {company} executed {swap_type} in anticipation of issuing fixed-rate notes, leaving {currency_code}{amount} {money_unit} of unrealized losses in OCI related to {swap_type} as of {month} {next_year}",
    "In {month} {year}, {company} entered into {swap_type} with a notional value of {currency_code}{amount} {money_unit} to hedge forecasted debt issuances, resulting in deferred losses recorded in accumulated OCI",
    "{company} designated {swap_type} in {month} {year} as {hedge_type} hedges against anticipated interest payments, with {currency_code}{amount} {money_unit} in fair value adjustments recorded in equity",
    "During {year}, {swap_type} were executed to lock in favorable rates prior to debt refinancing, with {currency_code}{amount} {money_unit} of accumulated losses deferred in other comprehensive income",
    "In {month} {year}, {company} entered into forward-starting {swap_type} in connection with planned debt offerings, recording {currency_code}{amount} {money_unit} of mark-to-market losses in OCI",
    "In {month} {year}, {company} utilized {swap_type} to manage interest rate risk, recognizing {currency_code}{amount} {money_unit} in unrealized gains in OCI as of {month} {next_year}",
    "During {year}, {company} executed {swap_type} to hedge against fluctuations in interest rates, with {currency_code}{amount} {money_unit} in deferred gains recorded in accumulated OCI",
    "{company} implemented {swap_type} in {month} {year} to stabilize borrowing costs, deferring {currency_code}{amount} {money_unit} of losses in other comprehensive income",
    "in the {quarter} quarter of {year}, {company} executed forward-starting {swap_type} to secure rates for future debt issuances, with {currency_code}{amount} {money_unit} in mark-to-market adjustments in OCI",
    "In {year}, {company} entered into {swap_type} to mitigate interest rate exposure, with {currency_code}{amount} {money_unit} in fair value changes deferred in equity",
    "In {month} {year}, {company} locked in rates using {swap_type}, recognizing {currency_code}{amount} {money_unit} in deferred losses within other comprehensive income",
    "during the {quarter} quarter of {year}, {company} executed {swap_type} to hedge planned bond issuances, with {currency_code}{amount} {money_unit} in unrealized losses recorded in OCI",
    "In {month} {year}, {swap_type} were used to manage exposure to interest rate volatility, resulting in {currency_code}{amount} {money_unit} of deferred gains in equity",
    "{company} entered into {swap_type} in {month} {year} to hedge forecasted interest payments, with {currency_code}{amount} {money_unit} in mark-to-market adjustments in OCI",
    "In {year}, {company} designated {swap_type} as hedges for anticipated debt, recording {currency_code}{amount} {money_unit} in fair value losses in accumulated OCI",
    "During {month} {year}, {company} implemented {swap_type} to secure favorable rates, with {currency_code}{amount} {money_unit} in unrealized gains deferred in OCI",
    "in the {quarter} quarter of {year}, {swap_type} were executed to manage interest rate risk on future borrowings, with {currency_code}{amount} {money_unit} in losses recorded in equity",
    "{company} used {swap_type} in {month} {year} to hedge against rising interest rates, deferring {currency_code}{amount} {money_unit} in mark-to-market losses in OCI",
    "In {month} {year}, {company} entered into {swap_type} with a notional value of {currency_code}{amount} {money_unit}, resulting in deferred gains recorded in accumulated OCI",
    "During {year}, {company} executed {swap_type} to lock in rates for planned financings, with {currency_code}{amount} {money_unit} in fair value adjustments in OCI",
    "In {month} {year}, {company} designated forward-starting {swap_type} as {hedge_type} hedges, recognizing {currency_code}{amount} {money_unit} in unrealized losses in equity",
    "{company} implemented {swap_type} in the {quarter} quarter of {year} to stabilize interest costs, with {currency_code}{amount} {money_unit} in deferred losses recorded in OCI",
    "In {month} {year}, {swap_type} were entered to hedge anticipated debt offerings, resulting in {currency_code}{amount} {money_unit} of mark-to-market gains in accumulated OCI",
]

ir_active_position_template = [
    "Outstanding swaps at year-end {year} effectively convert the hedged portion of debt to floating rates",
    "As of {month} {end_day}, {year}, {swap_type} with a notional amount of {currency_code}{notional} {money_unit} are designated as fair value hedges",
    "At year-end {year}, {company} holds {swap_type} with a total notional value of {currency_code}{notional} {money_unit} to manage debt-related interest rate risk",
    "As of {month} {year}, {company}’s outstanding {swap_type} have a notional value of {currency_code}{notional} {money_unit}, hedging fixed-rate obligations",
    "{company}’s active {swap_type} at year-end {year} have a total notional value of {currency_code}{notional} {money_unit}, designated as fair value hedges",
    "As of {month} {year}, {swap_type} with a notional amount of {currency_code}{notional} {money_unit} are in place to convert fixed-rate debt to floating rates",
    "At year-end {year}, {swap_type} with a notional value of {currency_code}{notional} {money_unit} are active to hedge fixed-rate debt obligations",
]

ir_optional_templates = [
    "In anticipation of issuing fixed-rate debt, {company} may use {swap_type} that are designated as {hedge_type} hedges to hedge against changes in interest rates that could impact expected future issuances of debt",
    "{company} utilizes {swap_type} designated as {hedge_type} hedges to lock in favorable interest rates prior to anticipated debt issuances",
    "To hedge interest rate exposure on forecasted debt offerings, {company} may enter into {swap_type} designated as {hedge_type} hedges",
    "{swap_type} are employed to mitigate the risk of rising interest rates on planned fixed-rate debt issuances",
    "{company} uses {swap_type} as {hedge_type} hedges to secure interest rates for future debt issuances",
    "In preparation for debt offerings, {company} may designate {swap_type} as {hedge_type} hedges to manage interest rate risk",
    "To protect against interest rate volatility, {company} employs {swap_type} for planned fixed-rate debt issuances",
    "{swap_type} are utilized as {hedge_type} hedges to lock in rates for anticipated debt financings",
    "{company} may enter into {swap_type} to hedge interest rate risk on forecasted debt issuances",
    "In anticipation of bond issuances, {swap_type} are designated as {hedge_type} hedges to stabilize future interest costs",
    "{company} uses {swap_type} to mitigate interest rate fluctuations on planned debt offerings",
    "{swap_type} are designated as {hedge_type} hedges to secure rates for future fixed-rate debt",
    "To manage interest rate exposure, {company} employs {swap_type} for anticipated debt issuances",
    "{company} may utilize {swap_type} as {hedge_type} hedges to lock in rates prior to debt financings",
    "{swap_type} are used to hedge against rising interest rates for planned debt issuances",
    "In preparation for fixed-rate debt, {company} designates {swap_type} as {hedge_type} hedges",
    "{company} employs {swap_type} to stabilize interest rates for forecasted bond issuances",
    "{swap_type} are implemented as {hedge_type} hedges to manage risk on future debt offerings",
    "To secure favorable rates, {company} may use {swap_type} for anticipated fixed-rate debt",
    "{company} designates {swap_type} as {hedge_type} hedges to mitigate interest rate risk on planned financings",
    "{company} manages its cash flow interest rate risk by using {swap_type}, where at quarterly intervals the difference between fixed contract rates and floating rate interest amounts calculated by reference to the agreed notional principal amounts are exchanged",
    "{company} utilizes {swap_type} to manage cash flow interest rate exposure, with quarterly settlements based on the differential between fixed and floating rates on notional amounts",
    "Cash flow interest rate risk is managed through {swap_type} with quarterly net settlements calculated on agreed notional principal amounts",
    "{company} employs {swap_type} converting floating rate exposure to fixed rates, with quarterly exchange of payment differentials based on notional values",
]

# Interest Rate (IR) Debt Optimization Templates
ir_debt_optimization_templates = [
    "{company} uses {instrument_list} to optimize the interest rate profile of its debt portfolio, converting portions of fixed-rate debt to floating-rate instruments",
    "To manage borrowing costs, {company} employs {instrument_list} to adjust the effective interest rate composition of outstanding debt",
    "{company} implements {instrument_list} to reduce interest rate volatility on its debt obligations",
    "As part of its debt strategy, {company} utilizes {instrument_list} to transform fixed-rate debt into variable-rate debt where appropriate",
    "To hedge against rising interest rates, {company} applies {instrument_list} to modify the interest rate characteristics of its borrowings",
    "{company} uses {instrument_list} to manage the interest rate exposure of its long-term debt portfolio",
    "The company employs {instrument_list} to convert portions of debt into instruments with more favorable interest rate terms",
    "{company} optimizes its debt by using {instrument_list} to balance fixed and floating rate obligations",
    "To stabilize interest expense, {company} applies {instrument_list} to its debt portfolio, managing cash flow risk",
    "{company} manages interest rate risk on forecasted debt issuances using {instrument_list} to adjust the effective interest profile",
]
